### PR TITLE
Added functionality + bug correction

### PR DESCRIPTION
**Pull request by muchu999**
-Fixed concurrency problem 
-Made all the attributes available in the app interface (old interface still available)
-Added a few more selections for  writeInterval and changed scheduling accordingly

### CODE REVIEW

**Comment by ogiewon** [comment]
I am no longer using this integration, and thus I cannot personally test it.  If you are 100% certain that this version is better and more reliable than the current version, I will merge this pull request. Also, is this version backwards compatible for existing users if they simply upgrade their existing code? Please let me know what you think.

**Comment by muchu999** [comment]
Yes, it is backward compatible and better in my opinion. I was happy with listing the code in the Hubitat forum thread until now but someone asked that I put it in Github. Not really pushing for it.

**Comment by ogiewon** [comment]
OK, it is merged!  Have fun!

**Comment by ogiewon** [comment]
Would you like to become a contributor to this repo?  It needs someone to take of it... ;)

**Comment by muchu999** [comment]
Yes you can make me a contributor, I don't expect much action, this project is a bit quiet...

**Comment by ogiewon** [comment]
@tooluser and @csteele-PD  - Can one of you please add @muchu999 as a contributor to this InfluxDB repository so they can make code changes without needing approval to merge/modify?  Thanks!

**Pull request merged**
