### PR TITLE
InfluxDB2.x support

### PR DESCRIPTION
**Pull request by Mavrrick**
This pull request will integrate changes to support influxdb 2.x 

There is also a current bug when installed for the first time if all setup is completed the app will not finish initializing all values or subscribe to events. Those steps were broken out to a initialization module and that module is called when installed or updated.

### CODE REVIEW

**Comment by dennypage** [comment]
Probably easier to get someone to review things if you submit narrow targeted PRs, and avoid superfluous changes (like encodeCredentialsBasic).

**Comment by Mavrrick** [comment]
The addition to add support for Influx DB v2.x was taken from a previous PR I found in a fork. Listed earlier. To support that it did appear it needed a fair amount of additions.

All of the changes I made were to port those additions to the current code base. that includes the change for encode CredentialsBasic. That particular change may not be needed, but since it was updated in the port that does do a fair amount of updates to how the smartapp connections including authentication to the remote database i didn't want to exclude it. I have these changes working on my dev hub.

The only addition to the port was to break out the initialization steps into their own module. That was to fix a issue where influxDB Logger doesn't seem to initialize the complete setup until you open it a second time and click done so it runs the update()

**Comment by adambrand** [comment]
Thanks for this PR! Have been using it without issue for several days now. Hopefully it gets merged in soon.

**Comment by dennypage** [comment]
There are a lot of changes in this PR unrelated to InfluxDB 2 support. Please break the PR into discrete / targeted PRs that can be more easily reviewed and tested. Note also that the code still needs to continue to support operation with InfluxDB 1.X.

**Pull request closed without merging**
