### PR TITLE
Update basic authorization and headers to actually function

### PR DESCRIPTION
**Pull request by ianpalencar**
The core issue here is that the header
`"Authorization : Basic username:password"`
was being converted to
`"Authorization : b8fa3912de691bcc6a408e1ef3accf0d"`
instead of
`"Authorization : Basic 390ae80ed318d2db67fe631024466b8c"`

This would result in 401 errors coming back from an endpoint which uses authorization, preventing any sort of data submission.
Additionally, updated the POST params to split concerns up some, facilitating easier future modifications of query parameters and the like.

### CODE REVIEW

**Comment by biocomp** [comment]
Oops, I just made a similar fix here (but also with adding tests): #7. It'd be nice to have some pull requests merged :)

**Comment by ianpalencar** [comment]
Tests are definitely helpful! I think it'd make sense to have a tested version over just the raw change for sure. I was originally trying to get myself unstuck and figured I'd throw something onto a pull request. This issue was also resolved as part of #6 via cherrypicking the auth fix from this pull request, so it seems rather popular.

**Comment by biocomp** [comment]
I see you did a bit more fixing than I. Do you want to review my pull request, suggest those fixes, and perhaps this gets merged sooner? I'll add them and add tests for your changes too.

**Comment by dennypage** [comment]
This PR appears stale and has conflicts with existing code. If the PR is still pertinent, please resolve conflicts and re-open. Thanks.

**Pull request closed without merging**
